### PR TITLE
remove very long warning cycle

### PR DESCRIPTION
**Pull request by visr**
On Julia 0.4-RC2, with the new deprecation warnings, I got stuck in a loop of deprecation warnings, regarding the Union{} deprecation. This new deprecation was not included yet in #32, so I added it to those commits. Also removes all other warnings on 0.4-RC2.

How exactly this loop can happen I do not understand, but this solves it. I'm likely not the only one with this problem, but it's likely WinRPM/Windows related, see https://groups.google.com/forum/#!topic/julia-users/OPugaioAGUU

### CODE REVIEW

**Comment by yuyichao** [comment]
It's probably not an infinite loop but the slow down caused by the deprecation warnings.

**Comment by visr** [comment]
I tried to write a program to determine if it was an infinite loop but couldn't manage. However Johan on the mailing list found that it finishes when left overnight. Nevertheless it would be good to merge this soon, if all is ok.

**Comment by mlubin** [comment]
Why is travis failing?

**Comment by tkelman** [comment]
The tests are segfaulting on anything except 0.3. No idea why.

**Comment by visr** [comment]
Indeed, I just changed the travis file. Interestingly the 0.4 segfault does turn into a
```
ERROR: LoadError: ReadOnlyMemoryError()
 in xp_make_parser at /home/travis/.julia/v0.5/LibExpat/src/LibExpat.jl:92
```
at the same location.

**Comment by visr** [comment]
@tkelman travis osx also segfaults. I also stopped extending `Base.find`, `find` is now no longer exported. The only unqualified usages of `find` I could find in registered packages were in `AWS.jl` from @amitmurthy

**Comment by tkelman** [comment]
Okay I forgot that I have commit access here, I'm going to merge this since it's a clear improvement but we still need to debug the segfault. This might be above our knowledge of the library or julia ccall failure modes, we'll have to see.

**Comment by visr** [comment]
Okay thanks for that, will you also tag a new release?

**Comment by tkelman** [comment]
This passes for me locally so the segfault might be a travis-only issue? ref https://github.com/amitmurthy/LibExpat.jl/pull/29#issuecomment-95076207

If I don't hear anything soon from @amitmurthy saying otherwise I guess I will tag a release.

**Comment by musm** [comment]
hi @visr  what was the motivation behind https://github.com/JuliaIO/LibExpat.jl/pull/37/commits/9db4b04cc6e497023090266e2aec025722388984 
"change String to AbstractString" 

thanks!

**Comment by tkelman** [comment]
String used to be an astract type.

**Pull request merged**
