### PR TITLE
Track 0.4 syntax, bring back 0.3 compatibility, modernize testing

### PR DESCRIPTION
**Pull request by garborg**
@amitmurthy, thanks for all your work on this package -- we've just adopted it in [OpenStreetMap.jl](https://github.com/tedsteiner/OpenStreetMap.jl).

Happy to help you set up Travis and Coveralls for this package if that's new to you.

### CODE REVIEW

**Comment by amitmurthy** [comment]
Cool. Thanks.

**Comment by amitmurthy** [comment]
Have added you as a collaborator - should help with setting up Travis/Coveralls and any other changes.

**Comment by garborg** [comment]
Great. The flip is switched on at Coveralls.io. For Travis, only admin have the permissions required to set that hook -- if you sign in there with your GitHub id and flip the switch for this repo, both will be enabled.

**Comment by amitmurthy** [comment]
I switched on the following:

```
Build only if .travis.yml is present ON OFF
Build pushes ON OFF
Build pull requests
```

**Comment by garborg** [comment]
Perfect.

**Pull request merged**
