### PR TITLE
removed warnings + imported base functions

### PR DESCRIPTION
**Pull request by SimonDanisch**
Uhm, just noticed I already made a pull request for this that never got merged.... Well this one has some more additions.

### CODE REVIEW

**Comment by SimonDanisch** [comment]
still segfaulting, great :D

**Comment by SimonDanisch** [comment]
Hi, 
can this get merged and tagged, since it seems like the segfault is unrelated?!
Would be lovely not to have one gazillion warnings when building something ;) It gives you that uneasy feel even if the build is successful.

Thanks,
Simon

**Comment by yuyichao** [comment]
Note that with recently added deprecation warnings this is making WinRPM output on AppVeyor unreadable [e.g.](https://ci.appveyor.com/project/mlubin/jump-jl/build/1.0.1507/job/6ilxij66cjwpwx3b) .

**Comment by EricForgy** [comment]
Out of curiosity, what is holding up this pull request?

I'm new to Github and Julia and when I saw the deprecation warning on master, I wrongfully presumed that if it was still on master I should go ahead and fix it and submit a pull request (trying to do whatever little I can to help out). Then I subsequently learned that another pull request fixing the same thing was submitted 25 days ago.

I see checks are failing but that seems to not be related to the pull request. Still learning the ropes so thanks for patience :)

**Comment by tkelman** [comment]
Cc @amitmurthy please go through these

**Comment by tkelman** [comment]
included (and tweaked a little) in #37

**Pull request closed without merging**
