### PR TITLE
Create appveyor.yml

### PR DESCRIPTION
**Pull request by tkelman**
will need to be enabled

### CODE REVIEW

**Comment by tkelman** [comment]
ping @amitmurthy could you turn this on?

**Comment by ranjanan** [comment]
Bump!

**Comment by amitmurthy** [comment]
I guess it should be in Settings -> Services. Couldn't find Appveyor there. What is it called?

**Comment by tkelman** [comment]
No, you enable it through a webhook. Sign up on appveyor then enable the repo through their projects page.

**Comment by amitmurthy** [comment]
Done.

**Pull request merged**
