### PR TITLE
float and int parsing and conversion for 5.0

### PR DESCRIPTION
**Pull request by beOn**

### CODE REVIEW

**Comment by musm** [comment]
If you would like a couple of tests would be very welcome to make sure we catch these out

**Comment by tkelman** [comment]
@musm don't do "Rebase and merge," github does not include the reference to the PR # in the commit message when you do that.

And you should generally leave PR's open for longer on packages that you're not the sole author of. I've warned you about this before.

**Comment by fuzzybear3965** [comment]
@tkelman, forgive me for intruding. I don't contribute to this package. But, your last comment is a bit strange. If a collaborator (which implies status) wants to merge in a pull request then they shouldn't have to wait for some arbitrary length of time.

I think it's important to remember that Julia exists in a non-profit context and we're all contributing our time because we think our work is valuable. No one out here is rushing to merge PRs to meet deadlines (because we don't have them). If a PR is merged in, then it must be that the work was thought to be beneficial to the project.

Also, with the power of git it's easy to revert small PRs if we really have to.

**Comment by tkelman** [comment]
@musm has not had contributor access here for long at all. Code review matters, particularly people who are depending on this package.

**Comment by fuzzybear3965** [comment]
Right, but because he (gender assumption) is a contributor it means that he's trusted. If I'm not mistaken, you're also not the project maintainer. Also, I see that the merge failed to pass CI testing, but that doesn't imply there wasn't code review. The tests may need to be changed to reflect that the package is working. In that case, the changes to the useable part of the code base would be fine.

I respect your ideas, I just think that this particular commit may have been a weak place to voice them. All that happened was the introduction of `parse` and `int` -> `Int`. If people who rely on this package have problems then they can raise an issue :). We have them; we might as well use them.

How long would you want someone to wait before merging in a PR as a contributor?

**Comment by musm** [comment]
In this commit,  `parsefloat` was deprecated in 0.5 and thus these methods no longer work on 0.5 (it wasn't being tested for). Similar with the other changes. 

The nightly failures are unrelated and due to a new world error related to callbacks. The tests pass on 0.4 and 0.5.

The PR is uncontroversial bug fix (thank you @beOn).

**Comment by beOn** [comment]
Sure thing :)

**Comment by tkelman** [comment]
People who contribute to Julia and its packages are based all around the world. Given time zones, waiting at least a day for anything non-urgent to allow people to see, be aware of, and comment on a PR would be sufficient and recommended.

Given the lack of test coverage hitting these lines, it would have been very useful to add a test here.

**Comment by beOn** [comment]
Alas.

**Pull request merged**
