### PR TITLE
Use a typealias for Tuple{Symbol,Any} to resolve properly in macros

### LINKED ISSUE #28: ERROR: type: instantiate_type: expected TypeConstructor, got Type{(Any...,)}
The xml file looks okay here from a visual inspection (https://gist.github.com/392165b87c4139e4ce23, libxml2/LightXML also parse it okay), is expat wrong?
```
  | | |_| | | | (_| |  |  Version 0.4.0-dev+4346 (2015-04-19 04:12 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 3074b70* (3 days old master)
|__/                   |  x86_64-linux-gnu

shell> curl http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.1/repodata/repomd.xml > repomd.xml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1620  100  1620    0     0   4409      0 --:--:-- --:--:-- --:--:--  4414

julia> using LibExpat

julia> xml = xp_parse("repomd.xml")
ERROR: "ErrorException(\"Error parsing document : 0\"), syntax error, 1, 1, 1"
 in error at error.jl:19
 in xp_parse at /home/tkelman/.julia/v0.4/LibExpat/src/LibExpat.jl:289
```

On Windows I get a slightly different error, "not well-formed (invalid token), 1, 3, 3".

### PR DESCRIPTION
**Pull request by tkelman**
fixes #28

### CODE REVIEW

**Comment by tkelman** [comment]
this passes on 0.4 for me locally, on ubuntu 14.04

**Comment by tkelman** [comment]
I tried making a separate branch to test the docker worker, and unfortunately it still segfaults there... https://travis-ci.org/amitmurthy/LibExpat.jl/jobs/59514942

**Comment by amitmurthy** [comment]
LGTM. Please go ahead and merge.

**Comment by tkelman** [comment]
Thanks. It doesn't segfault when I locally run a docker container of Ubuntu precise, and download the same Julia nightly. Something particular about the Travis image I guess?

**Comment by amitmurthy** [comment]
I guess. Similar unexplained segfault in HTTPClient too.

**Pull request merged**
