### PR TITLE
Fix for new 0.4 Tuple type syntax

### PR DESCRIPTION
**Pull request by tkelman**
fix breakage caused by https://github.com/JuliaLang/julia/pull/10380

### CODE REVIEW

**Comment by tkelman** [comment]
Hm, seems to segfault on Travis. I can't reproduce locally on Linux, but I'm using Ubuntu 14.04 vs Travis is on 12.04.

**Comment by amitmurthy** [comment]
I think we should go ahead and merge this. There has been an unexplained (and yet unsolved) segfault with HTTPClient.jl on Travis too. I thought it may be due to the AMD CPUs that Travis uses.

**Comment by tkelman** [comment]
I don't see how this could make anything any worse...

Maybe give the docker-based workers a try via `sudo: false` ?

**Comment by amitmurthy** [comment]
>
> Maybe give the docker-based workers a try via sudo: false ?
>

I am not familiar with this mode of testing. How is it enabled?

**Comment by tkelman** [comment]
See http://docs.travis-ci.com/user/workers/container-based-infrastructure/

I think since you apparently don't need to apt-get anything here, it might just be adding a line `sudo: false` to your travis.yml? Maybe try it in a test branch first?

**Comment by amitmurthy** [comment]
Will test out the docket-based workers separately. Though http://docs.travis-ci.com/user/workers/container-based-infrastructure/ says the default behaviour if sudo is not detected is to use docker based containers.

**Comment by tkelman** [comment]
I think that only applies for new repos, not sure.

**Pull request merged**
